# Generated by Django 4.0.2 on 2022-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.TextField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('picture', models.ImageField(default='white.jpg', upload_to='')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
